version: '2'

services:

  lb:
    image: dockercloud/haproxy
    links:
      - websrv
    environment:
      - COOKIE=SRV insert indirect nocache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  websrv:
    build: ./web/Demo2App/Demo2App
    image: websrv
    environment:
      - COOKIE=SRV insert indirect nocache
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - 8081-8090:80
    depends_on:
      - sqlserver
  
  sqlserver:    
    build: ./db
    container_name: DBsrv
    ports:
      - '1433:1433'